home:
  path: /
  controller: App\Controller\HomeController::index

materiels:
  path : /materiels
  controller: App\Controller\MaterielsController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
