name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1 # or alternative dependency management
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
    - name: Run Mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'magestionmateriel' # Optional, default value is "test". The specified database which will be create
        mysql user: 'myadmin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: password
    - name: Linter
      run: php-cs-fixer fix --using-cache=no --rules=@Symfony src                                                                                                     
    - name: Test
      run: php bin/phpunit --coverage-text tests/



      
    
